### ISSUE TITLE
Footer is always detached from the literal foot of page

### ISSUE THREAD

**Issue by handelaar** [mysociety/alavetelitheme#100]
This fragment...

`
<a href="#content" class="show-with-keyboard-focus-only skip-to-link">Back to content</a>
`

...sits outside and after the footer on WDTK and lots of other sites, and causes a white space of approx 1em to appear underneath the footer. It's hideous. And if it's required, shouldn't it be *above* the footer anyway?

**Comment by wrightmartin** [comment]
@handelaar thanks for spotting that one, looks like a small bug to do with the positioning. I'll get that fixed right away

**Comment by zarino** [comment]
The gap is _not_ being caused by the "Back to content" link – `.show-with-keyboard-focus-only` positions the link absolutely, so it’s impossible for it to take up space in the page flow.

Instead, my hunch is that the gap is being caused by an unclosed `<div>` much further up the page. I’m hoping @wrightmartin will get a chance to fix that gap as part of https://github.com/mysociety/alaveteli/issues/4342#issuecomment-342435523

**Comment by zarino** [comment]
That said, removing the link from the DOM does close up the space. But we _do_ still have some sort of nesting error. Hmmm.

**Comment by wrightmartin** [comment]
> That said, removing the link from the DOM does close up the space. But we do still have some sort of nesting error. Hmmm.

It has no ```top``` declaration, adding it removes it from the document flow
