### ISSUE TITLE
before_filter is deprecated

### ISSUE THREAD

**Issue by garethrees** [mysociety/alavetelitheme#108]
Required by https://github.com/mysociety/alaveteli/issues/3969

```
$ BUNDLE_GEMFILE="Gemfile.rails5" bundle exec rspec spec/models/
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <class:Base> at /home/vagrant/alaveteli/lib/themes/alavetelitheme/lib/alavetelitheme.rb:12)
```

**Comment by garethrees** [comment]
Ah fixed in https://github.com/mysociety/alavetelitheme/commit/5417b988e276588883fbb416614a91f1b191f6ce – needed to update locally

**Comment by juanmartin** [comment]
hi
i'm facing an issue installing alaveteli
the rails-post-deploy script fails when installing theme
it says it should use before_action instead of before_filter
but when i try to modify the theme it says I have uncommited changes
is there a way to bypass this?

I tried a lot of themes, most of them face the same issue. I even stated false to the branch it has to use so that it uses master or whatever HEAD is at.

Help I can't finish installing Alaveteli.
Thx in adv.
cheers
